# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 14:53
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=255)),
                ('tab', models.CharField(max_length=255)),
                ('header', models.CharField(max_length=255)),
                ('functions', models.CharField(max_length=255)),
                ('data', models.TextField(max_length=255)),
                ('permissions', models.CharField(max_length=255)),
                ('updatedAt', models.DateTimeField(default=datetime.datetime.now, verbose_name='date created')),
                ('createdBy', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
    ]
