# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-06 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('attribute', models.CharField(max_length=255)),
                ('updatedBy', models.CharField(max_length=255)),
                ('references', models.CharField(max_length=255)),
                ('permissions', models.CharField(max_length=255)),
                ('updatedAt', models.CharField(max_length=255)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemical.Chemical')),
            ],
        ),
    ]
