# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-09 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemical', '0004_auto_20160809_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('updatedBy', models.CharField(max_length=255)),
                ('permissions', models.CharField(max_length=255)),
                ('updatedAt', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='references',
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='value',
        ),
        migrations.RemoveField(
            model_name='formula',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='formula',
            name='references',
        ),
        migrations.RemoveField(
            model_name='formula',
            name='value',
        ),
        migrations.RemoveField(
            model_name='project',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='project',
            name='references',
        ),
        migrations.RemoveField(
            model_name='project',
            name='value',
        ),
        migrations.AddField(
            model_name='attribute',
            name='chemical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemical.Chemical'),
        ),
    ]
