# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-10 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical', '0005_auto_20160809_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='updatedBy',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
