# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-10 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical', '0006_auto_20160810_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='permissions',
            field=models.CharField(default='All', max_length=255),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='updatedBy',
            field=models.CharField(default='Admin', max_length=255),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='permissions',
            field=models.CharField(default='All', max_length=255),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='updatedBy',
            field=models.CharField(default='Admin', max_length=255),
        ),
        migrations.AlterField(
            model_name='specification',
            name='permissions',
            field=models.CharField(default='All', max_length=255),
        ),
        migrations.AlterField(
            model_name='specification',
            name='updatedBy',
            field=models.CharField(default='Admin', max_length=255),
        ),
    ]
