# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-11 13:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical', '0010_auto_20160811_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='updatedAt',
            field=models.DateTimeField(default=1, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updatedAt',
            field=models.DateTimeField(default=1, verbose_name='date created'),
        ),
    ]
