# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-11 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemical', '0011_auto_20160811_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='row',
        ),
    ]
