# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-11 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical', '0014_auto_20160811_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='updatedAt',
            field=models.CharField(max_length=255),
        ),
    ]
