# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-11 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical', '0021_auto_20160811_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='row',
            field=models.IntegerField(),
        ),
    ]
