# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-15 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical', '0024_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batch',
            name='total',
            field=models.DecimalField(decimal_places=4, default=100.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='batch',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=7),
        ),
    ]
