# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-15 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical', '0025_auto_20160815_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='locked',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='total',
        ),
        migrations.AddField(
            model_name='formula',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formula',
            name='total',
            field=models.DecimalField(decimal_places=4, default=100.0, max_digits=7),
        ),
    ]
