# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-15 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemical', '0026_auto_20160815_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='chemical',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
