# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-15 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical', '0027_auto_20160815_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='codes',
            field=models.CharField(default='not', max_length=255),
        ),
        migrations.AddField(
            model_name='chemical',
            name='description',
            field=models.CharField(default='not', max_length=255),
        ),
        migrations.AddField(
            model_name='chemical',
            name='functions',
            field=models.CharField(default='not', max_length=255),
        ),
        migrations.AddField(
            model_name='chemical',
            name='regulatory',
            field=models.CharField(default='not', max_length=255),
        ),
    ]
