# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-24 15:53
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chemical', '0029_auto_20160819_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('permissions', models.CharField(max_length=255)),
                ('updatedAt', models.DateTimeField(default=datetime.datetime.now, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('permissions', models.CharField(max_length=255)),
                ('updatedAt', models.DateTimeField(default=datetime.datetime.now, verbose_name='date created')),
                ('createdBy', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='batch',
            name='chemical',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='formula',
        ),
        migrations.DeleteModel(
            name='Workbook',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='createdBy',
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='codes',
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='functions',
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='regulatory',
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='updatedBy',
        ),
        migrations.RemoveField(
            model_name='formula',
            name='locked',
        ),
        migrations.RemoveField(
            model_name='formula',
            name='name',
        ),
        migrations.RemoveField(
            model_name='formula',
            name='project',
        ),
        migrations.RemoveField(
            model_name='formula',
            name='total',
        ),
        migrations.RemoveField(
            model_name='formula',
            name='updatedBy',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updatedBy',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='updatedBy',
        ),
        migrations.AddField(
            model_name='chemical',
            name='createdBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formula',
            name='book',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='formula',
            name='createdBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formula',
            name='data',
            field=models.TextField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='formula',
            name='functions',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='formula',
            name='header',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='formula',
            name='tab',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='specification',
            name='createdBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.AddField(
            model_name='attribute',
            name='chemical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemical.Chemical'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='createdBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
